### ISSUE TITLE
IEでも一応見れるようにする

### ISSUE THREAD

**Issue by tossy310** [nishi-owls/nishi-owls#3]

**Comment by numa72** [comment]
IEでHPを確認したところ下記4点の異常がありました。1と4は直したいところかと思います。

1. プルダウンが常時垂れ下がったままになる

- トップページ

![IE_top_page_1](https://user-images.githubusercontent.com/89718422/131243606-1231bdc5-6202-4ddd-9798-f46f1617fd4a.png)

- ゲームレポート(試合結果)

![IE_game_page_game_report](https://user-images.githubusercontent.com/89718422/131243779-c30d7fd3-f211-4d90-96b4-8c090dce88e2.png)

2. 画像が縦長になる

- トップページ

![IE_top_page_2](https://user-images.githubusercontent.com/89718422/131243894-c88479e4-e8cc-4320-928a-fc1fba86878c.png)

- コーチ・スタッフ紹介

![IE_team_coach_stuff_face](https://user-images.githubusercontent.com/89718422/131244509-1f0fe04e-b688-45e4-a233-c5cdcef02ef9.png)

3. 試合予定と最近の結果がマス目にならない&横スクロールの一覧にならない

- 試合予定と最近の試合結果

 ![IE_game_page_recent_game](https://user-images.githubusercontent.com/89718422/131244081-622a6888-43a1-4f80-84de-b5c636f2ae57.png)

4. twitterの呟きが共有できない 

- 2021年度秋季都大会の組み合わせについて(トピックス)

![IE_topics_page_pairing_twitter](https://user-images.githubusercontent.com/89718422/131244119-2509add1-7d40-4624-a855-95fe76afbd39.png)

**Comment by tossy310** [comment]
@numa72 確認ありがとうございます。

1 の表示が出たままになってしまうのは避けたいですね。
ゲームレポートはこのままでも良いですが、サブメニューが隠されないのは流石に見た目がひどいですね。。。

4 については、twitterがIEのサポートをdropしているようなので、素直に諦めるので良いかなと思っています。
https://twittercommunity.com/t/removing-ie11-support-and-custom-link-colors-in-twitter-for-websites/131171

2,3は余裕があれば直しましょう。。。

**Comment by tossy310** [comment]
公開から1週間、IEユーザーは0.4%なので、「サブメニューが隠されない」問題だけ確認して、簡単に直せそうなら直す、それ以外は放置でいいかなと思っています。

**Comment by tossy310** [comment]
https://github.com/nishi-owls/nishi-owls/issues/3#issuecomment-917406445 の通り、最低限のfixを入れたので、他を優先すべく、これは閉じます。
