### ISSUE TITLE
Pagination の導入

### ISSUE THREAD

**Issue by tossy310** [nishi-owls/nishi-owls#37]
今後 topics の記事が増えたときのために、paginationを導入したい。

具体的には https://github.com/sverrirs/jekyll-paginate-v2 の topics の記事一覧 / tagごとの記事一覧への導入。 GitHub Actions でビルドするようになったので、今はv2が使える。

スマホデザインでは横2記事、PCデザインでは横3記事で表示しているので、1ページに掲載する記事数は6の倍数が適切。とりあえず12あたりでいいんじゃないかと思う。

**Comment by numa72** [comment]
順次対応するので、自分にアサインしてもらっても良いでしょうか？

**Comment by tossy310** [comment]
@numa72 

https://github.com/nishi-owls/nishi-owls/tree/paperLion ブランチにある記事が公開されると、topicsが9記事になり、春季都大会で2記事、1ヶ月中にもう1記事の追加が予想されるので、あと1ヶ月くらいで12記事に到達しそうなのですが、それくらいを目安にできそうでしょうか？

**Comment by tossy310** [comment]
> 1ヶ月中にもう1記事の追加

あと1ヶ月程度で、もう1つOBインタビュー記事の追加予定、です。

**Comment by tossy310** [comment]
既に記事数が12になり、そろそろ秋大会の組み合わせのお知らせを告知予定で、記事数が12を超えるので、 pagination が現実的に欲しいので important label 付けました
