### ISSUE TITLE
ヘッダーナビゲーションの下矢印アイコンを画像ではなくてCSSで生成する

### ISSUE THREAD

**Issue by tossy310** [nishi-owls/nishi-owls#4]
![image](https://user-images.githubusercontent.com/19281814/131243279-2b6a5b72-20e4-4502-bf5c-f3c534bd5281.png)

ここの白い三角形はCSSで作れるので、そうしたい。

今後のデザインの拡張や調整がしやすくなるはず。

**Comment by numa72** [comment]
こちらのissueひとまず、私のほうで対応します。

**Comment by tossy310** [comment]
ありがとうございます！

例えば about team ページの MORE のリンクの三角形はCSS生成になっているので、同様の形でできると思うので参考にしてください。
https://github.com/nishi-owls/nishi-owls/blob/1572fb356b09b2cd08758b88677e6cc5991de5fb/_sass/team.scss#L190-L201

**Comment by numa72** [comment]
こちら対応してプルリク出しました。
確認お願いします。
