### ISSUE TITLE
祝78期入学を作る

### ISSUE THREAD

**Issue by tossy310** [nishi-owls/nishi-owls#57]
昨年の例 https://github.com/nishi-owls/nishi-owls/pull/36

**Comment by tossy310** [comment]
具体的にやること
* トップページのスライドショーの画像を用意して追加する e.g. https://github.com/nishi-owls/nishi-owls/pull/36/files#diff-f046ebb10a95bbc0527a1abfe1ddb7e170c2f9d4d6a0bababeac1048d70cbb50
* ヘッダに祝入学、という文字を入れてクリックするとメッセージのページに飛ぶようにする e.g. https://github.com/nishi-owls/nishi-owls/pull/36/files#diff-c0311c1df17d5d714db46ca1401ad374a35de861a461d211c6c947f1b2194034

**Comment by numa72** [comment]
一応画像抜き(ファイル名は昨年に倣いwelcome78.jpgという体)でローカルでコード書きました。
画像はもうどっかに上がってますか？
画像あればそれ含めてプルリクします。

**Comment by tossy310** [comment]
画像まだ貰えてないです。再度聞いてみます

**Comment by tossy310** [comment]
いい感じの最新年度の画像が用意できなかったようなので、昨年と同じものをベースに作成しました [welcome78.zip](https://github.com/nishi-owls/nishi-owls/files/11121738/welcome78.zip)

ちなみに xcf ファイルは [GIMP](https://www.gimp.org/) のフォーマットで、フリーソフト・オープンスースで、環境によらずに開けると思います。commitにもxcfファイルを入れておいていただけると助かります。今後の素材の再利用時に便利なので。

**Comment by tossy310** [comment]
@numa72 これそろそろ戻したいですね。最近お願いが多いですが、こちらもよろしいでしょうか

**Comment by numa72** [comment]
気づかなくてごめん
やります！

**Comment by tossy310** [comment]
Closed via #68
