### ISSUE TITLE
"クリックできる要素同士が近すぎます" モバイルユーザビリティエラー from Google Search Console

### ISSUE THREAD

**Issue by tossy310** [nishi-owls/nishi-owls#9]
https://support.google.com/webmasters/answer/9063469#touch_elements_too_close

おそらく右上のSNSのリンク。

**Comment by numa72** [comment]
こちらの方自分で引き受けます

**Comment by tossy310** [comment]
@numa72 

ありがとうございます。現状わかっていることを以下にシェアします。

右上のSNSのアイコンを padding 等含めて 48px 以上にしなければいけないのですが、css の `vw` を使用しているために、表示サイズが場合によっては小さすぎることが問題だと思っています。

かといって、単純に `min-width: 48px` と指定するだけでは現状のデザインが崩れてしまうので、簡単には解決できず、今のところ保留状態になっています。

**Comment by numa72** [comment]
@tossy310 
思ったよりややこしいんですね。
こちらの方、上記の対応のアイデアが浮かんでから引き受けますね。

**Comment by tossy310** [comment]
よく分からないけど、この警告が出なくなったので閉じます
